default_context:
  project_name: 'web api'
  project_slug: 'web-api'
  domain_main: 'web-api.com'
  domain_staging: 'stag.web-api.com'
  docker_swarm_stack_name_main: 'web-api-com'
  docker_swarm_stack_name_staging: 'stag-web-api-com'
  secret_key: 'changethis'
  first_superuser: 'admin@web-api.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.web-api.com, https://stag.web-api.com, https://web-api.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@web-api.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@web-api.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'web-api.com'
  traefik_constraint_tag_staging: 'stag.web-api.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
