[tool.poetry]
name = "web_api"
version = "0.1.0"
description = ""
authors = ["Christopher Dignam <chris@dignam.xyz>"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.4"
flask = "^1.1"
flask_login = "^0.4.1"
flask_migrate = "^2.5"
flask_sqlalchemy = "^2.4"
requests = "^2.22"
yarl = "^1.4"
python-dotenv = "^0.10.5"
pytest-flask-sqlalchemy = "^1.0"
psycopg2 = "^2.8"

[tool.poetry.dev-dependencies]
pylint = "^2.4"
pytest = "^5.3"
mypy = "^0.761.0"
isort = "^4.3"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
